Выполнен sprint_11
bukhmillerEd/ImageFeed pull request #4
Opened 2023-05-16 09:22 UTC by bukhmillerEd

2023-05-16 17:59 UTC, IBDesignable requested changes

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +                    DispatchQueue.main.async {
UIBlockingProgressHUD.dismiss() - тоже изменяет UI, тогда почему  он не вызывается в блоке main.async?

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +        UIBlockingProgressHUD.show()
лучше этот код вызывать перед тем, как фетчить токен, неожиданных ошибок будет меньше

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
>                  case .success(let bearerToken):
вызывать OAuth2Service.shared.fetchAuthToken(code: code)  внутри DispatchQueue.main.async не нужно, вызов уже происходит на главном потоке

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Models/UserResult.swift
> +    }
Кроме CodingKeys, существует еще другой способ работать со snake_case структурами с бекенда, JSONDecoder умеет настраиваться специальным образом, чтобы преобразовывать самостоятельно названия в snake_case обратно в camelCase

Подробнее тут
https://nemecek.be/blog/90/how-to-decode-snake-case-with-codable

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Models/ProfileResult.swift
> +    let lastName: String
Это свойство тоже может быть опциональным, можно проверить отредактировав профиль в Unsplash: 

<img width="751" alt="Снимок экрана 2023-05-09 в 21 07 21" src="https://github.com/bukhmillerEd/ImageFeed/assets/121577115/047d2d99-3bb5-4d9d-a51a-eaea690f8bfe">

Если это не исправить, то при декодинге ты получишь ошибку и профиль не загрузится

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +            case .failure(_):
можно упрощать
```suggestion
            case .failure:
```

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +        ProfileService.shared.fetchProfile(token) { [weak self] result  in
```suggestion
        ProfileService.shared.fetchProfile(token) { [weak self] result in
```

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +        ProfileService.shared.fetchProfile(token) { [weak self] result  in
перед вызовом хорошо бы показать крутилку

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +                DispatchQueue.main.async {
а здесь крутилку отменить, потому что будет показан алерт

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +                        self?.switchToTabBarController()
аналогично, нужно отжать лоадер прежде чем показывать новый экран

2023-05-16 17:59 UTC, IBDesignable commented on ImageFeed/Services/ProfileImageService.swift
> +
нотификацию надо опубликовать на главной очереди

2023-05-16 18:02 UTC, IBDesignable commented
Я не смогла проверить приложение, после старта черный экран. Видимо потому что приложение токен помнит, а профиль получить не смогло. 
Ожидаю, что здесь будет крутиться индикатор загрузки, а под ним экран сплеша, пока не загрузится профиль или не вернется ошибка. 
![RocketSim_Recording_iPhone_11_2023-05-16_20 59 43](https://github.com/bukhmillerEd/ImageFeed/assets/121577115/fa6f84ff-6e30-4953-b07b-d3f7aa9df709)

Профиль загружается сейчас не верно: случай c last name не учтен. К тому же не весь код, который обновляет UI, оборачивается на главную очередь – это тоже может быть причиной ошибки. 

нужно разобраться и прислать работу еще раз

2023-05-17 07:00 UTC, bukhmillerEd commented
> Я не смогла проверить приложение, после старта черный экран. Видимо потому что приложение токен помнит, а профиль получить не смогло. Ожидаю, что здесь будет крутиться индикатор загрузки, а под ним экран сплеша, пока не загрузится профиль или не вернется ошибка. ![RocketSim_Recording_iPhone_11_2023-05-16_20 59 43](https://user-images.githubusercontent.com/121577115/238732606-fa6f84ff-6e30-4953-b07b-d3f7aa9df709.gif)
> 
> Профиль загружается сейчас не верно: случай c last name не учтен. К тому же не весь код, который обновляет UI, оборачивается на главную очередь – это тоже может быть причиной ошибки.
> 
> нужно разобраться и прислать работу еще раз

Приложение крашится (судя по видео крашится) или черный экран во время загрузки профиля (судя по тексту) ?

2023-05-17 10:50 UTC, bukhmillerEd commented
Если я правильно понял, основная проблема заключалась в том что после запуска приложения был черный экран. Приложение не крэшилось. Если все таки был крэш, то просьба скинуть поподробнее инфу. А то у меня не получилось воспроизвести проблему из-за которой возможет крэш, и не понятно где он может быть.

2023-05-17 12:00 UTC, IBDesignable commented
нет не краш, просто похоже после запроса профиля не презентовался экран/или ошибка. 
Для начала давай исправим ошибку с загрузкой профиля, возможно дальше будет яснее в чем причина либо болячка уйдет

2023-05-17 15:14 UTC, bukhmillerEd commented
> нет не краш, просто похоже после запроса профиля не презентовался экран/или ошибка.
> Для начала давай исправим ошибку с загрузкой профиля, возможно дальше будет яснее в чем причина либо болячка уйдет
Спасибо за уточнение! Вроде разобрался, был косяк в том что сверстанный в сториборде контроллер создавал через консруктор AuthViewController(), а не получал его через сториборд. Это поправил вместе с другими замечаниями, сделал второй коммит в этом пулреквесте, и ссылку на пулреквест скинул в практикуме

2023-05-17 19:49 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +                        self?.switchToTabBarController()
Не хватает DispatchQueue.main.async

2023-05-17 19:50 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +                        self?.switchToTabBarController()
Обращай внимание на фиолетовые ворнинги: 
<img width="1001" alt="Снимок экрана 2023-05-17 в 22 46 50" src="https://github.com/bukhmillerEd/ImageFeed/assets/121577115/e85be45f-be6a-4006-ab96-95c029734725">

то что в симуляторе не упало, у пользователя закончится крашем

2023-05-18 10:09 UTC, bukhmillerEd commented on ImageFeed/Presentation/SplashViewController.swift
> +                        self?.switchToTabBarController()
Видел про этот ворнинг. Но думал что Xcode хочет чтобы я обернул строку return UIApplication.shared.windows.first в DispatchQueue.main.async {}, а в учебнике она не обернута, поэтому засомневался. Только сейчас понял, после того как поправил замечание, что Xcode проанализировал, что есть вызов не из главного потока и поэтому ругался, после исправления ворнинг пропал.
Подскажи пожалуйста, можно ли было обернуть UIApplication.shared.windows.first в DispatchQueue.main.async {}, чтобы избежать того что где - то случайно вызвали эту функцию не на главном потоке? И будет ли это являться ошибкой или плохим кодстайлом, если где то вызвали на главном и тут еще снова повторно будет переход на главный поток ?

2023-05-19 13:47 UTC, IBDesignable commented on ImageFeed/Presentation/SplashViewController.swift
> +                        self?.switchToTabBarController()
> Подскажи пожалуйста, можно ли было обернуть UIApplication.shared.windows.first в DispatchQueue.main.async {}, чтобы избежать того что где - то случайно вызвали эту функцию не на главном потоке? 

Внутри вычислимого свойство window **нет**. потому что вычислимое свойство требует возвращенного типа (return), а замыкание DispatchQueue.main.async { } говорит программе - вот код, его выполни пожалуйста в следующий такт [ранлупа](https://stevenpcurtis.medium.com/what-is-a-runloop-anyway-swift-and-ios-guide-aa574577331b#:~:text=A%20run%20loop%20keeps%20your,What%20is%20a%20RunLoop%20Anyway%3F). (это такой системный цикл, в котором происходят обновления UI) 
То есть аснихронный вызов, ничего не возвращает. Только помещает задачи на отложенное возвращение.

Но ты бы мог схитрить, и делать это внутри функций show/dismiss. потому что там возвращать ничего не надо.

И как ты уже правильно предположил,  

> И будет ли это являться ошибкой или плохим кодстайлом, если где то вызвали на главном и тут еще снова повторно будет переход на главный поток ?

да, это скорее костыль, чем решение. Перенаправлять с главного на главный никто не запрещает и беды это не даст. Но это усложняет поиск ошибок, потому что это не предсказуемое поведение.

Допустим ты так сделаешь и для лоадера убережешься, дальше ты пишешь код тебя какой-то комплишен: 

``` swift
func someNetworkFunctuon()  {
    fetchData { [weak self] result 
     switch result {
     case .success: 
        UIBlockingProgressHUD.dismiss() 
        showNextScreen() 

     case .failure: 
       UIBlockingProgressHUD.dismiss()
       showError()
    } 
    }
}
```

И я как читающая  этот код – предполагаю, что fetchData возвращает completion уже на главной очереди, или может быть внутри showNextScreen/showError - сделано оборачинвание на главную очередь. Чтобы это выяснить, мне нужно специально пойти и убедиться в этом.

В этом плане авторы предлагают сетевой запрос как раз возвращать на главный поток, прежде чем его разворачивать на экранах. Это простой путь, потому что один раз напишешь - больше не думаешь.

Я же придерживаюсь правила – что переводить на главную очередь нужно как можно ближе к местам обновления UI. То есть если оба свитча делают что-то, что обновляет ui - я бы весь свитч тогда обернула на главную очередь. Да это бывает не так красиво. Но зато хорошо считываются намерения. Здесь уже не получится не думать о том, как код выполняется. Но в этом и суть - так ты быстрее запомнишь про это правило, и будешь писать надежный код на автомате. А когда придет время устраиваться в команду – просто подстроишься под их способ справления с этой задачей)


Итак коротко, ответ на твой вопрос: **так лучше не делать, это костыль.** Лучше переводить на главную очередь тот код, который точно получен с другой очереди но **должен запускаться на главной очереди**.

2023-05-19 19:37 UTC, merged