Sprint 12
bukhmillerEd/ImageFeed pull request #5
Opened 2023-05-28 18:43 UTC by bukhmillerEd

2023-05-29 16:01 UTC, protos17 requested changes

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
>      @IBOutlet weak var photo: UIImageView!
Рекомендую сделать все @IBOutlet приватными, создать модель для ячейки, а для конфигурации сделать отдельный метод:
func configure(with: model: ImagesListCellModel) {
cellImage.image = model.image
...
}
struct ImagesListCellModel {
let image: UIImage?
...
}

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBAction func likeButtonClicked(_ sender: UIButton) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +            favoritesButton.setImage(UIImage(named: "Favorites Active"), for: .normal)
Рекомендую избегать дублирование кода и сначала создать константу картинки, которую потом присвоить кнопке:
let image = UIImage(named: isLike ? "Favorites Active" : "Favorites No Active")

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        imagesListService.changeLike(token: token, photoId: photo.id, isLike: !photo.isLiked) { result in
Рекомендую здесь тоже указать как слабую ссылку - weak self

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                    self.photos[indexPath.row].isLiked = !self.photos[indexPath.row].isLiked
Для смены значения на противоположный рекомендую использовать toggle:
self.photos[indexPath.row].isLiked.toggle()

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/Models/Photo.swift
> +    var id: String
Все поля, кроме isLiked рекомендую сделать константами - let, потому что они не изменяются

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/Presentation/ProfileViewController.swift
> -        print("logoutButtonWasPressed")
Здесь нужно добавить показ алерта, а после нажатия на "Да", тогда уже удалять все и открывать SplashViewController

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/Presentation/ProfileViewController.swift
> +        //let sb = UIStoryboard(name: "Main", bundle: .main)
Лишний закомментированный код рекомендую удалять

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +    func fetchPhotosNextPage(_ token: String) {
Токен рекомендую не передавать как аргумент функции, а создать в классе экземпляр этого токена и обращаться к нему

2023-05-29 16:01 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +            request = URLRequest(url: DefaultBaseURL).likeRequest(photoId: photoId)
Рекомендую тоже подумать как избавиться от дублирования, у этих методов отличаются только httpMethod

2023-05-29 20:07 UTC, bukhmillerEd commented on ImageFeed/ImagesList/ImagesListCell.swift
>      @IBOutlet weak var photo: UIImageView!
Попытался так сделать, но возникла сложность, картинка то у нас загружается асинхронно. Вот такой код (картинка не стает в ячейку) 
    func configCell(for cell: ImagesListCell, with indexPath: IndexPath) {
        cell.delegate = self

        let dateLabel = UILabel()
        dateLabel.text = photos[indexPath.row].createdAt == nil ? "" : dateFormatter.string(from: photos[indexPath.row].createdAt!)

        let favoritesButton = UIButton()
        let namePhotoButton = photos[indexPath.row].isLiked ? "Favorites Active" : "Favorites No Active"
        favoritesButton.setImage(UIImage(named: namePhotoButton), for: .normal)

        let photo = UIImageView()
        let url = URL(string: photos[indexPath.row].thumbImageURL)
        photo.kf.indicatorType = .activity
        photo.kf.setImage(with: url, placeholder: UIImage(named: "stub")) { [weak self] _ in
            guard let self else { return }
            let modelCell = ImagesListCellModel(photo: photo,
                                                dateLabel: dateLabel,
                                                favoritesButton: favoritesButton)
            cell.configure(with: modelCell)
            self.tableView.reloadRows(at: [indexPath], with: .automatic)
        }
    }

2023-05-30 08:24 UTC, bukhmillerEd commented on ImageFeed/Services/ImagesListService.swift
> +    func fetchPhotosNextPage(_ token: String) {
Перед вызовом функции я проверяю что токен существует
   if let token = OAuth2TokenStorage().token {
                imagesListService.fetchPhotosNextPage(token)
    }
Эту проверку тоже лучше убрать, или в класс перенести, чтобы вообще запрос не делать если вдруг токена нет?

2023-05-30 08:27 UTC, protos17 commented on ImageFeed/Services/ImagesListService.swift
> +    func fetchPhotosNextPage(_ token: String) {
Лучше делать эту проверку в начале функции, чтобы при отсутствии токена функция прерывалась

2023-05-30 09:36 UTC, bukhmillerEd commented
Поправил замечания, остались некоторые вопросы:
1) Вы писали: "При открытии детального экрана сначала в левом верхнем углу появляется лоадер, а лишь затем посередине экрана." - Не очень понял проблему. А что такое детальный экран? Это экран, который с полным фото? Вроде проверил все экраны и не увидел где лоадер появляется в верхнем левом углу. Можно попросить приложить скриншот?
2) "Кнопка лайка слишком маленькая" Сейчас кнопка 44 на 44, и вроде по рекомендациям apple это минимальная рекомендуемая величина 
3) По поводу модели для cell. Если я правильно понимаю, то если мы используем модель, то сразу все оутлеты ячейки будут обновляться из модели в один момент, но у нас картинка загружается чуть позже. Выше я приложил код, как я попробовал реализовать, но у меня почему то картинка не встала в ячейку вообще. Я в ту строну мыслю,  при реализации кода  с использованием модели?

2023-05-31 09:29 UTC, protos17 commented
> Поправил замечания, остались некоторые вопросы:
> 
> 1. Вы писали: "При открытии детального экрана сначала в левом верхнем углу появляется лоадер, а лишь затем посередине экрана." - Не очень понял проблему. А что такое детальный экран? Это экран, который с полным фото? Вроде проверил все экраны и не увидел где лоадер появляется в верхнем левом углу. Можно попросить приложить скриншот?
> 2. "Кнопка лайка слишком маленькая" Сейчас кнопка 44 на 44, и вроде по рекомендациям apple это минимальная рекомендуемая величина
> 3. По поводу модели для cell. Если я правильно понимаю, то если мы используем модель, то сразу все оутлеты ячейки будут обновляться из модели в один момент, но у нас картинка загружается чуть позже. Выше я приложил код, как я попробовал реализовать, но у меня почему то картинка не встала в ячейку вообще. Я в ту строну мыслю,  при реализации кода  с использованием модели?

1. Такое поведение при повторном открытии экрана с полным фото:
![Снимок экрана 2023-05-31 в 12 27 16](https://github.com/bukhmillerEd/ImageFeed/assets/84586624/3ee4b600-d546-45a3-b35e-ab10dea84d62)
2. Сама кнопка у тебя правильного размера, а вот картинка кнопки меньше, чем в макете
3. Написал тебе в комментариях, как это реализовать

2023-05-31 09:29 UTC, protos17 approved these changes

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
>  }
Рекомендую создать типа такой модели для ячейки:

struct ImagesListCellModel {
    let photoName: String
    let date: String
    let favoritesName: String
    var completion: (() -> Void)
}

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +
Здесь рекомендую написать типа такого метода, а IBOutlet сделать приватными:

    func configureCell(with model: ImagesListCellModel) {
        photo.kf.indicatorType = .activity
        dateLabel.text = model.date
        favoritesButton.setImage(UIImage(named: model.favoritesName), for: .normal)
        let url = URL(string: model.photoName)
        photo.kf.setImage(with: url, placeholder: UIImage(named: "stub"), completionHandler: { _ in
            model.completion()
        })
    }

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>          return imageListCell
Здесь перед return рекомендую убрать метод configCell(for: imageListCell, with: indexPath) и вызвать:

        imageListCell.delegate = self
        let date = photos[indexPath.row].createdAt == nil ? "" : dateFormatter.string(from: photos[indexPath.row].createdAt!)
        let favoritesName = photos[indexPath.row].isLiked ? "Favorites Active" : "Favorites No Active"
        let photoName = photos[indexPath.row].thumbImageURL
        let model = ImagesListCellModel(photoName: photoName, date: date, favoritesName: favoritesName, completion: { [weak self] in
            self?.tableView.reloadRows(at: [indexPath], with: .automatic)
        })
        imageListCell.configureCell(with: model)

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
>      @IBOutlet weak var photo: UIImageView!
Мы в модели должны передавать данные для настройки, а не сами UI элементы

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>  class ImagesListViewController: UIViewController {
Рекомендую указать как final

2023-05-31 09:29 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>      func configCell(for cell: ImagesListCell, with indexPath: IndexPath) {
Метод configCell нужно писать в самой ячейке

2023-05-31 13:10 UTC, bukhmillerEd commented
Спасибо за подробный комментарий! я учту и допилю на каникулах, сейчас уже малость отстаю

2023-05-31 13:11 UTC, merged